config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #read all tasks
  get "tasks", to: "tasks#index"
  #create a task
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  #read one tasks
  get "tasks/:id", to: "tasks#show", as: :show_task
  #update a task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id/edit", to: "tasks#update", as: :task
  #delete a task
  delete "tasks/:id", to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :find_task, only: [:show, :edit, :update, :destroy]

    def index
        @tasks = Task.all
    end

    def show
    end

    def new
        @tasks = Task.new
    end

    def create
        @tasks = Task.new(task_params)
        @tasks.save
        redirect_to tasks_path
    end

    def edit
    end

    def update
        @tasks.update(task_params)
        redirect_to show_task_path(@tasks)
    end

    def destroy
        @tasks.destroy
        redirect_to tasks_path
    end

    private

    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end

    def find_task
        @tasks = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@tasks) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.label :completed, "task completed!" %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/index.html.erb
<h1>Lits of taks</h1>
<%= link_to 'Create New task', tasks_new_path %>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, show_task_path(task) %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<h1><%= @tasks.title %></h1>
<p><%= @tasks.details %><%= @tasks.completed %></p>

<%= link_to 'Edit', edit_task_path(@tasks) %>
<%= link_to 'Delete', delete_task_path(@tasks), method: :delete, data: { confirm: 'Are you sure?'} %>
<%= link_to 'Tasks List', tasks_path %>